fix(*): fix security vulnerability and database selection
bungle/lua-resty-session pull request #177
Opened 2024-04-29 13:56 UTC by outsinre

1. If two redis clients share the same connection but use different database, both clients might receive error upon set/get data.
2. If a client without authentication shares a connection that is authenticated by other clients, this client bypass ACL.

FTI-5839

2024-05-02 13:55 UTC, bungle commented
@outsinre could you add tests?

2024-05-02 13:57 UTC, bungle commented
@outsinre can you also explain security vulnerability? I guess this is somewhat related to connection pooling that can be shared by some other app?

2024-05-02 14:00 UTC, bungle commented
This library supports `pool_name`:
https://github.com/bungle/lua-resty-session/blob/master/lib/resty/session/redis.lua#L191

So I guess it is just the default pool name generation?

2024-05-02 14:06 UTC, bungle requested changes

2024-05-02 14:06 UTC, bungle commented on lib/resty/session/utils.lua
> +end
Almost no difference to (what is differences really to `hmac_sha256`):
https://github.com/bungle/lua-resty-session/blob/e7eab2060753bb01bb164c11db8fb1a7be457116/lib/resty/session/utils.lua#L769

2024-05-02 14:07 UTC, bungle commented
To be honest, I don't see any problem with this library. Should we have default pool name generation? Not sure. Should it be part of `resty.redis` library, why here?

2024-07-17 09:27 UTC, closed without merging

2024-07-18 05:26 UTC, outsinre commented
Deprecated by #179